# Generated by Django 5.1 on 2024-09-10 23:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tentativas', models.IntegerField()),
                ('tempo', models.IntegerField()),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['tentativas', 'tempo', '-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('tempo', models.TimeField(auto_now_add=True)),
                ('tentativas', models.IntegerField()),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memoria.jogo')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
