# Generated by Django 5.1 on 2024-09-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='tempo',
            field=models.CharField(max_length=10),
        ),
    ]
